[package]
name = "mtw-transport"
description = "Transport layer for mtwRequest — WebSocket, HTTP, and SSE over tokio"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["websocket", "transport", "tokio", "realtime", "mtw"]
categories = ["web-programming::websocket", "network-programming", "asynchronous"]

[dependencies]
mtw-protocol = { workspace = true }
mtw-core = { workspace = true }
mtw-codec = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
ulid = { workspace = true }
