//! Userspace TCP/IP stack on top of [`crate::wireguard::WireGuardTunnel`]
//! — phase B.2.
//!
//! Bridges between application sockets (the `WgTcpStream` exposed in
//! B.3) and the inner-IP-packet ports of the WG tunnel via
//! [smoltcp](https://docs.rs/smoltcp). One `WgStack` runs per tunnel
//! instance.
//!
//! ## Architecture
//!
//! ```text
//! [smoltcp socket]                                      ← B.3: TcpStream API
//!       ↑↓                       (poll() drives socket
//!       ↑↓                        state machines)
//!  [smoltcp Interface] ←→ [WgDevice] ←→ [WireGuardTunnel channels]
//!                                              ↑↓
//!                                    [boringtun encap/decap]
//!                                              ↑↓
//!                                       [UDP socket to WG peer]
//! ```
//!
//! ## What B.2 ships
//!
//! - [`WgDevice`]: `smoltcp::phy::Device` impl that takes packets out
//!   of the tunnel's inbound channel and pushes outbound packets back
//!   through the tunnel.
//! - [`WgStack`]: owns the smoltcp `Interface` + `SocketSet` + the
//!   `WgDevice` and runs a poll task at ~50 ms cadence.
//! - Plumbing for opening sockets (`add_tcp_socket`, returns a handle).
//!
//! What's still to come in **B.3**:
//! - `WgTcpStream`: a tokio `AsyncRead + AsyncWrite` wrapper around a
//!   smoltcp TCP socket handle (with proper waker integration).
//! - reqwest custom `Connector` so HTTP rides this stack.
//! - librqbit dialer for BitTorrent peer wires.

use std::sync::Arc;
use std::time::{Duration, Instant};

use mtw_core::MtwError;
use smoltcp::iface::{Config, Interface, SocketSet};
use smoltcp::phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken};
use smoltcp::time::Instant as SmolInstant;
use smoltcp::wire::{HardwareAddress, IpAddress, IpCidr, Ipv4Address, Ipv6Address};
use tokio::sync::{mpsc, Mutex};

use crate::wireguard::WireGuardTunnel;

/// Inner MTU for the WG tunnel. Outer (UDP) MTU is typically 1500;
/// boringtun's data overhead is 32 bytes; we leave some room for
/// safety. Standard WG MTU is 1420.
pub const WG_INNER_MTU: usize = 1420;

/// How often to poll smoltcp's socket state machines. Affects latency
/// for "outbound IP packet ready to send" — lower = lower latency at
/// the cost of more CPU.
const STACK_POLL_INTERVAL: Duration = Duration::from_millis(50);

/// Per-tunnel addressing config. The local IP is what smoltcp uses as
/// the source address for any packet generated by sockets on this
/// stack — must match the IP your WG peer assigned you.
#[derive(Debug, Clone)]
pub struct WgAddrConfig {
    /// IPv4 address assigned by the WG peer (e.g. Mullvad gives you
    /// `10.x.y.z/32`). Required.
    pub local_ipv4: Option<(Ipv4Address, u8)>,
    /// IPv6 address assigned by the WG peer. Optional — most WG
    /// providers issue one if you ask.
    pub local_ipv6: Option<(Ipv6Address, u8)>,
}

impl WgAddrConfig {
    /// Build from string forms (the way they appear in TOML).
    /// Accepts `10.64.0.5` (assumes /32), `10.64.0.5/24`, `fd00::5/128`.
    pub fn from_strings(
        ipv4: Option<&str>,
        ipv6: Option<&str>,
    ) -> Result<Self, MtwError> {
        let v4 = ipv4
            .map(|s| parse_v4_cidr(s))
            .transpose()?;
        let v6 = ipv6
            .map(|s| parse_v6_cidr(s))
            .transpose()?;
        if v4.is_none() && v6.is_none() {
            return Err(MtwError::Config(
                "wireguard: at least one of local_ipv4/local_ipv6 must be set".into(),
            ));
        }
        Ok(Self {
            local_ipv4: v4,
            local_ipv6: v6,
        })
    }
}

fn parse_v4_cidr(s: &str) -> Result<(Ipv4Address, u8), MtwError> {
    let (addr, prefix) = match s.split_once('/') {
        Some((a, p)) => (a, p.parse::<u8>().map_err(|e| {
            MtwError::Config(format!("wireguard: invalid v4 prefix '{}': {}", p, e))
        })?),
        None => (s, 32),
    };
    let octets: Vec<u8> = addr
        .split('.')
        .map(|o| o.parse::<u8>())
        .collect::<Result<_, _>>()
        .map_err(|e| MtwError::Config(format!("wireguard: invalid v4 addr '{}': {}", addr, e)))?;
    if octets.len() != 4 {
        return Err(MtwError::Config(format!(
            "wireguard: v4 addr must have 4 octets, got '{}'",
            addr
        )));
    }
    Ok((
        Ipv4Address::from([octets[0], octets[1], octets[2], octets[3]]),
        prefix,
    ))
}

fn parse_v6_cidr(s: &str) -> Result<(Ipv6Address, u8), MtwError> {
    let (addr, prefix) = match s.split_once('/') {
        Some((a, p)) => (a, p.parse::<u8>().map_err(|e| {
            MtwError::Config(format!("wireguard: invalid v6 prefix '{}': {}", p, e))
        })?),
        None => (s, 128),
    };
    let parsed: std::net::Ipv6Addr = addr.parse().map_err(|e| {
        MtwError::Config(format!("wireguard: invalid v6 addr '{}': {}", addr, e))
    })?;
    // smoltcp re-exports `core::net::Ipv6Addr` as `Ipv6Address`, so
    // construct via the std API.
    Ok((Ipv6Address::from(parsed.octets()), prefix))
}

/// `smoltcp::phy::Device` impl that ferries IP packets between the WG
/// tunnel and the smoltcp stack.
///
/// - `receive()` pulls one decrypted packet out of the inbound channel
///   (the WG driver pushes them after decapsulate). Returns `None` if
///   the queue is empty — smoltcp will retry on the next poll.
/// - `transmit()` returns a token that, when consumed by smoltcp, ships
///   a packet through the tunnel's outbound channel (encapsulate +
///   UDP send happen inside the WG driver).
pub struct WgDevice {
    inbound: mpsc::UnboundedReceiver<Vec<u8>>,
    outbound: mpsc::UnboundedSender<Vec<u8>>,
    mtu: usize,
}

impl WgDevice {
    pub fn new(
        inbound: mpsc::UnboundedReceiver<Vec<u8>>,
        outbound: mpsc::UnboundedSender<Vec<u8>>,
    ) -> Self {
        Self {
            inbound,
            outbound,
            mtu: WG_INNER_MTU,
        }
    }
}

impl Device for WgDevice {
    type RxToken<'a> = WgRxToken;
    type TxToken<'a> = WgTxToken<'a>;

    fn receive(
        &mut self,
        _timestamp: SmolInstant,
    ) -> Option<(Self::RxToken<'_>, Self::TxToken<'_>)> {
        let packet = self.inbound.try_recv().ok()?;
        Some((
            WgRxToken { buffer: packet },
            WgTxToken {
                outbound: &self.outbound,
            },
        ))
    }

    fn transmit(&mut self, _timestamp: SmolInstant) -> Option<Self::TxToken<'_>> {
        Some(WgTxToken {
            outbound: &self.outbound,
        })
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();
        caps.medium = Medium::Ip;
        caps.max_transmission_unit = self.mtu;
        caps
    }
}

pub struct WgRxToken {
    buffer: Vec<u8>,
}

impl RxToken for WgRxToken {
    fn consume<R, F>(self, f: F) -> R
    where
        F: FnOnce(&[u8]) -> R,
    {
        f(&self.buffer)
    }
}

pub struct WgTxToken<'a> {
    outbound: &'a mpsc::UnboundedSender<Vec<u8>>,
}

impl<'a> TxToken for WgTxToken<'a> {
    fn consume<R, F>(self, len: usize, f: F) -> R
    where
        F: FnOnce(&mut [u8]) -> R,
    {
        let mut buf = vec![0u8; len];
        let r = f(&mut buf);
        // Best-effort send. If the WG driver has gone away the channel
        // is closed; we drop the packet — at higher layers (smoltcp's
        // retransmit) will figure it out.
        let _ = self.outbound.send(buf);
        r
    }
}

/// Smoltcp interface + socket-set + driver task. One per WG tunnel.
///
/// The driver polls smoltcp's `Interface` at `STACK_POLL_INTERVAL`,
/// which advances socket state machines and gives the device a chance
/// to drain inbound packets / emit outbound packets. Sockets must be
/// added via [`add_tcp_socket`](Self::add_tcp_socket) and accessed
/// through `SocketSet` (B.3 will wrap this in `WgTcpStream`).
pub struct WgStack {
    pub(crate) inner: Arc<WgStackInner>,
}

pub(crate) struct WgStackInner {
    /// Interface + sockets are mutated together. smoltcp's Interface
    /// holds a reference to the device, which we move INTO the lock.
    pub(crate) state: Mutex<WgStackState>,
}

pub(crate) struct WgStackState {
    pub(crate) iface: Interface,
    pub(crate) sockets: SocketSet<'static>,
    pub(crate) device: WgDevice,
    /// Monotonic clock origin so smoltcp's Instant remains stable
    /// across polls.
    started: Instant,
}

impl WgStackState {
    fn now(&self) -> SmolInstant {
        SmolInstant::from_millis(self.started.elapsed().as_millis() as i64)
    }
}

impl WgStack {
    /// Build the stack on top of an already-connected WG tunnel.
    /// Consumes the tunnel's inbound receiver (single-consumer) and
    /// clones its outbound sender.
    pub async fn new(
        mut tunnel: WireGuardTunnel,
        addr: WgAddrConfig,
    ) -> Result<(Self, WireGuardTunnel), MtwError> {
        let inbound_rx = tunnel
            .take_inbound_receiver()
            .ok_or_else(|| MtwError::Internal("wireguard: stack already attached to this tunnel".into()))?;
        let outbound_tx = tunnel.outbound_sender();

        let device = WgDevice::new(inbound_rx, outbound_tx);

        // smoltcp Interface needs a `&mut Device` for construction —
        // we set up addrs after creating it. We use Medium::Ip (no
        // link-layer header).
        let mut device = device;
        let started = Instant::now();
        let now = SmolInstant::from_millis(started.elapsed().as_millis() as i64);
        let mut iface = Interface::new(
            Config::new(HardwareAddress::Ip),
            &mut device,
            now,
        );

        // Apply IP addresses.
        iface.update_ip_addrs(|ips| {
            if let Some((v4, prefix)) = addr.local_ipv4 {
                let _ = ips.push(IpCidr::new(IpAddress::Ipv4(v4), prefix));
            }
            if let Some((v6, prefix)) = addr.local_ipv6 {
                let _ = ips.push(IpCidr::new(IpAddress::Ipv6(v6), prefix));
            }
        });

        let sockets = SocketSet::new(Vec::new());

        let state = WgStackState {
            iface,
            sockets,
            device,
            started,
        };
        let inner = Arc::new(WgStackInner {
            state: Mutex::new(state),
        });

        // Driver: poll smoltcp at fixed cadence so socket state
        // machines advance.
        let inner_for_driver = inner.clone();
        tokio::spawn(async move {
            run_stack_driver(inner_for_driver).await;
        });

        Ok((Self { inner }, tunnel))
    }

    /// Drive a single poll synchronously. Tests use this; the
    /// background driver task does it on a timer in production.
    pub async fn poll_once(&self) {
        let mut state = self.inner.state.lock().await;
        let now = state.now();
        let WgStackState {
            iface,
            sockets,
            device,
            ..
        } = &mut *state;
        iface.poll(now, device, sockets);
    }

    /// Returns true when the stack has at least one configured local
    /// IP. Used by tests / sanity checks before opening sockets.
    pub async fn has_address(&self) -> bool {
        let state = self.inner.state.lock().await;
        state.iface.ip_addrs().iter().any(|_| true)
    }
}

async fn run_stack_driver(inner: Arc<WgStackInner>) {
    let mut interval = tokio::time::interval(STACK_POLL_INTERVAL);
    loop {
        interval.tick().await;
        let mut state = inner.state.lock().await;
        let now = state.now();
        let WgStackState {
            iface,
            sockets,
            device,
            ..
        } = &mut *state;
        iface.poll(now, device, sockets);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wireguard::{WireGuardKeys, WireGuardTunnel};
    use base64::Engine;
    use rand::RngCore;

    fn random_key_b64() -> String {
        let mut k = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut k);
        base64::engine::general_purpose::STANDARD.encode(k)
    }

    #[test]
    fn parses_v4_with_prefix() {
        let cfg =
            WgAddrConfig::from_strings(Some("10.64.0.5/24"), None).unwrap();
        let (addr, prefix) = cfg.local_ipv4.unwrap();
        assert_eq!(addr, Ipv4Address::new(10, 64, 0, 5));
        assert_eq!(prefix, 24);
    }

    #[test]
    fn parses_v4_default_prefix_32() {
        let cfg = WgAddrConfig::from_strings(Some("10.64.0.5"), None).unwrap();
        let (_, prefix) = cfg.local_ipv4.unwrap();
        assert_eq!(prefix, 32);
    }

    #[test]
    fn parses_v6_with_prefix() {
        let cfg =
            WgAddrConfig::from_strings(None, Some("fd00::5/64")).unwrap();
        let (_, prefix) = cfg.local_ipv6.unwrap();
        assert_eq!(prefix, 64);
    }

    #[test]
    fn rejects_no_addresses() {
        let r = WgAddrConfig::from_strings(None, None);
        assert!(r.is_err());
    }

    #[test]
    fn rejects_garbage_v4() {
        assert!(WgAddrConfig::from_strings(Some("not.an.address"), None).is_err());
    }

    #[tokio::test]
    async fn device_returns_none_when_inbound_empty() {
        let (_in_tx, in_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let (out_tx, _out_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let mut dev = WgDevice::new(in_rx, out_tx);
        let now = SmolInstant::from_millis(0);
        assert!(dev.receive(now).is_none());
    }

    #[tokio::test]
    async fn device_passes_inbound_packet_through_rxtoken() {
        let (in_tx, in_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let (out_tx, _out_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let mut dev = WgDevice::new(in_rx, out_tx);
        let payload = vec![0x45, 0x00, 0x00, 0x14]; // bogus IPv4 header start
        in_tx.send(payload.clone()).unwrap();

        let now = SmolInstant::from_millis(0);
        let (rx, _tx) = dev.receive(now).expect("packet should be visible");
        let observed = rx.consume(|bytes| bytes.to_vec());
        assert_eq!(observed, payload);
    }

    #[tokio::test]
    async fn txtoken_pushes_to_outbound_channel() {
        let (_in_tx, in_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let (out_tx, mut out_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let mut dev = WgDevice::new(in_rx, out_tx);
        let now = SmolInstant::from_millis(0);
        let tx = dev.transmit(now).unwrap();
        tx.consume(8, |buf| {
            assert_eq!(buf.len(), 8);
            buf.copy_from_slice(b"abcdefgh");
        });
        let received = out_rx.recv().await.unwrap();
        assert_eq!(&received, b"abcdefgh");
    }

    #[tokio::test]
    async fn stack_attaches_to_unconnected_tunnel() {
        // We don't drive the WG handshake here — the stack only
        // needs the channels, which `new()` already wired up. This
        // verifies the smoltcp Interface accepts our WgDevice.
        let listener = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let listener_addr = listener.local_addr().unwrap();
        let keys = WireGuardKeys::from_strings(
            &random_key_b64(),
            &random_key_b64(),
            None,
            &listener_addr.to_string(),
            None,
        )
        .unwrap();
        let tunnel = WireGuardTunnel::new(keys).await.unwrap();

        let addr = WgAddrConfig::from_strings(Some("10.64.0.5/32"), None).unwrap();
        let (stack, _tunnel) = WgStack::new(tunnel, addr).await.unwrap();
        assert!(stack.has_address().await);

        // Driver poll shouldn't panic.
        stack.poll_once().await;
    }

    #[tokio::test]
    async fn stack_refuses_double_attach() {
        let listener = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let listener_addr = listener.local_addr().unwrap();
        let keys = WireGuardKeys::from_strings(
            &random_key_b64(),
            &random_key_b64(),
            None,
            &listener_addr.to_string(),
            None,
        )
        .unwrap();
        let tunnel = WireGuardTunnel::new(keys).await.unwrap();

        let addr = WgAddrConfig::from_strings(Some("10.64.0.5/32"), None).unwrap();
        let (_stack, tunnel) = WgStack::new(tunnel, addr.clone()).await.unwrap();
        // Inbound receiver was consumed — second attach should fail.
        let r = WgStack::new(tunnel, addr).await;
        assert!(r.is_err());
    }
}
