pub mod rsi;
pub mod macd;
pub mod ema_crossover;
pub mod bollinger;
pub mod supertrend;
pub mod adx;
pub mod stochastic_rsi;
pub mod ichimoku;
pub mod obv;
pub mod kelly;
pub mod linear_regression;
pub mod vwap;
pub mod williams_r;
pub mod ensemble;
pub mod regime;
// Standard TA — batch 2
pub mod stochastic;
pub mod cci;
pub mod mfi;
pub mod aroon;
pub mod parabolic_sar;
pub mod donchian;
pub mod elder_ray;
pub mod keltner;
pub mod atr_channel;
pub mod choppiness;
pub mod chaikin_mf;
pub mod vwma_trend;
pub mod fibonacci;
pub mod pivot_points;
pub mod squeeze;

pub use rsi::RsiFormula;
pub use macd::MacdFormula;
pub use ema_crossover::EmaCrossoverFormula;
pub use bollinger::BollingerFormula;
pub use supertrend::SuperTrendFormula;
pub use adx::AdxFormula;
pub use stochastic_rsi::StochasticRsiFormula;
pub use ichimoku::IchimokuFormula;
pub use obv::ObvFormula;
pub use kelly::KellyFormula;
pub use linear_regression::LinearRegressionFormula;
pub use vwap::VwapFormula;
pub use williams_r::WilliamsRFormula;
pub use ensemble::EnsembleFormula;
pub use regime::RegimeFormula;
pub use stochastic::StochasticFormula;
pub use cci::CciFormula;
pub use mfi::MfiFormula;
pub use aroon::AroonFormula;
pub use parabolic_sar::ParabolicSarFormula;
pub use donchian::DonchianFormula;
pub use elder_ray::ElderRayFormula;
pub use keltner::KeltnerFormula;
pub use atr_channel::AtrChannelFormula;
pub use choppiness::ChoppinessFormula;
pub use chaikin_mf::ChaikinMfFormula;
pub use vwma_trend::VwmaTrendFormula;
pub use fibonacci::FibonacciFormula;
pub use pivot_points::PivotPointsFormula;
pub use squeeze::SqueezeFormula;

use crate::formula::FormulaRegistry;

/// Register all built-in formulas
pub fn register_all(registry: &mut FormulaRegistry) {
    registry.register(Box::new(RsiFormula));
    registry.register(Box::new(MacdFormula));
    registry.register(Box::new(EmaCrossoverFormula));
    registry.register(Box::new(BollingerFormula));
    registry.register(Box::new(SuperTrendFormula));
    registry.register(Box::new(AdxFormula));
    registry.register(Box::new(StochasticRsiFormula));
    registry.register(Box::new(IchimokuFormula));
    registry.register(Box::new(ObvFormula));
    registry.register(Box::new(KellyFormula));
    registry.register(Box::new(LinearRegressionFormula));
    registry.register(Box::new(VwapFormula));
    registry.register(Box::new(WilliamsRFormula));
    registry.register(Box::new(EnsembleFormula));
    registry.register(Box::new(RegimeFormula));
    // Standard TA — batch 2
    registry.register(Box::new(StochasticFormula));
    registry.register(Box::new(CciFormula));
    registry.register(Box::new(MfiFormula));
    registry.register(Box::new(AroonFormula));
    registry.register(Box::new(ParabolicSarFormula));
    registry.register(Box::new(DonchianFormula));
    registry.register(Box::new(ElderRayFormula));
    registry.register(Box::new(KeltnerFormula));
    registry.register(Box::new(AtrChannelFormula));
    registry.register(Box::new(ChoppinessFormula));
    registry.register(Box::new(ChaikinMfFormula));
    registry.register(Box::new(VwmaTrendFormula));
    registry.register(Box::new(FibonacciFormula));
    registry.register(Box::new(PivotPointsFormula));
    registry.register(Box::new(SqueezeFormula));
}
