use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Per-profile encryption config — egress mode for traffic generated by
/// this torrent. Mirrors `mtw_net::OutboundProfile` plus a few torrent-
/// specific knobs that don't belong to the generic HTTP factory (e.g.,
/// peer-traffic policy when announces ride a different profile from peers).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EncryptionProfile {
    /// Direct outbound. Default.
    Direct,

    /// Tunnel HTTP traffic (announces, webseeds) through a proxy. Peer
    /// traffic still goes direct unless `peer_traffic` overrides.
    Proxy {
        url: String,
        #[serde(default)]
        no_proxy: Vec<String>,
        /// Optional override for raw peer connections. Defaults to
        /// `direct` because most proxy types (HTTP, SOCKS5 plain) cannot
        /// carry uTP / TCP-on-arbitrary-port for peer wires.
        #[serde(default)]
        peer_traffic: Option<PeerTrafficPolicy>,
    },

    /// Tor SOCKS5 — alias for Proxy with peer_traffic forced to `clear`
    /// and a clear note that peer connections are NOT anonymized.
    TorSocks {
        #[serde(default = "default_tor_socks")]
        socks5: String,
    },

    /// Reserved for future userspace WireGuard.
    Wireguard {
        private_key: String,
        peer_public_key: String,
        endpoint: String,
        #[serde(default = "default_allowed_ips")]
        allowed_ips: Vec<String>,
        #[serde(default)]
        dns: Vec<String>,
    },
}

fn default_tor_socks() -> String {
    "127.0.0.1:9050".into()
}

fn default_allowed_ips() -> Vec<String> {
    vec!["0.0.0.0/0".into(), "::/0".into()]
}

/// What route peer wire connections (TCP/uTP) should take when the
/// announce profile already tunnels HTTP. `Same` reuses the announce
/// profile (only meaningful for full VPN profiles); `Clear` keeps peers
/// on the host's default route.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PeerTrafficPolicy {
    Same,
    Clear,
}

impl EncryptionProfile {
    pub fn label(&self) -> String {
        match self {
            Self::Direct => "Direct (no extra encryption)".into(),
            Self::Proxy { url, .. } => format!("Proxy: {}", url),
            Self::TorSocks { socks5 } => format!("Tor SOCKS5: {} (announces only)", socks5),
            Self::Wireguard { endpoint, .. } => format!("WireGuard → {}", endpoint),
        }
    }

    pub fn is_available(&self) -> bool {
        match self {
            Self::Direct => true,
            Self::Proxy { .. } => true,
            Self::TorSocks { .. } => true,
            // Userspace WG ships only when the boringtun integration is
            // wired up. Currently always reports unavailable.
            Self::Wireguard { .. } => false,
        }
    }

    pub fn unavailable_reason(&self) -> Option<&'static str> {
        match self {
            Self::Wireguard { .. } => Some("wireguard support not yet built"),
            _ => None,
        }
    }
}

/// Top-level configuration for the torrent module. Lives under
/// `[torrent]` in `mtw.toml`, with profiles loaded from a separate file
/// (default `~/.config/mtwrequest/torrent-profiles.toml`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TorrentConfig {
    /// Master switch. Default true; set false to skip module init even
    /// when the crate is compiled in.
    #[serde(default = "true_default")]
    pub enabled: bool,

    /// Where downloaded files live. Default
    /// `${XDG_DATA_HOME:-~/.local/share}/mtwrequest/torrents`.
    #[serde(default)]
    pub storage_path: Option<PathBuf>,

    /// Optional storage cap in bytes. New `add` calls fail with a clear
    /// error once this is reached.
    #[serde(default)]
    pub storage_quota_bytes: Option<u64>,

    /// Where the data-plane HTTP server binds. Default `127.0.0.1:9999`.
    #[serde(default = "default_http_listen")]
    pub http_listen: String,

    /// Profile used for `add` calls that don't specify one. Default `clear`.
    #[serde(default = "default_profile")]
    pub default_profile: String,

    /// Path to the profiles TOML file. Loaded eagerly during `init`.
    #[serde(default)]
    pub profiles_file: Option<PathBuf>,

    /// Inline profile definitions (alternative to `profiles_file`).
    #[serde(default)]
    pub profiles: HashMap<String, EncryptionProfile>,

    /// Streaming tuning. Reasonable defaults are baked in.
    #[serde(default)]
    pub streaming: StreamingConfig,
}

fn true_default() -> bool {
    true
}

fn default_http_listen() -> String {
    "127.0.0.1:9999".into()
}

fn default_profile() -> String {
    "clear".into()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamingConfig {
    #[serde(default = "default_prefetch")]
    pub prefetch_window_bytes: u64,
    #[serde(default = "default_read_buffer")]
    pub read_buffer_bytes: u64,
}

fn default_prefetch() -> u64 {
    16 * 1024 * 1024
}

fn default_read_buffer() -> u64 {
    1024 * 1024
}

impl Default for StreamingConfig {
    fn default() -> Self {
        Self {
            prefetch_window_bytes: default_prefetch(),
            read_buffer_bytes: default_read_buffer(),
        }
    }
}

impl Default for TorrentConfig {
    fn default() -> Self {
        let mut profiles = HashMap::new();
        profiles.insert("clear".into(), EncryptionProfile::Direct);
        Self {
            enabled: true,
            storage_path: None,
            storage_quota_bytes: None,
            http_listen: default_http_listen(),
            default_profile: default_profile(),
            profiles_file: None,
            profiles,
            streaming: StreamingConfig::default(),
        }
    }
}

impl TorrentConfig {
    /// Resolve the storage directory, falling back to
    /// `${XDG_DATA_HOME:-~/.local/share}/mtwrequest/torrents`.
    pub fn resolved_storage_path(&self) -> PathBuf {
        if let Some(p) = &self.storage_path {
            return p.clone();
        }
        let base = std::env::var("XDG_DATA_HOME")
            .ok()
            .map(PathBuf::from)
            .or_else(|| std::env::var("HOME").ok().map(|h| PathBuf::from(h).join(".local/share")))
            .unwrap_or_else(|| PathBuf::from("/var/lib"));
        base.join("mtwrequest").join("torrents")
    }

    /// Inject the `clear` profile if missing, so callers can rely on it.
    pub fn ensure_clear_profile(&mut self) {
        self.profiles
            .entry("clear".into())
            .or_insert(EncryptionProfile::Direct);
    }

    /// Load a profiles file if `profiles_file` is set, merging into
    /// `self.profiles`. Inline profiles take precedence on key collision.
    pub fn load_profiles_file(&mut self) -> Result<(), mtw_core::MtwError> {
        let Some(path) = self.profiles_file.clone() else {
            return Ok(());
        };
        let raw = std::fs::read_to_string(&path).map_err(|e| {
            mtw_core::MtwError::Config(format!(
                "torrent: read profiles_file '{}': {}",
                path.display(),
                e
            ))
        })?;
        #[derive(serde::Deserialize)]
        struct ProfilesDoc {
            #[serde(default)]
            profiles: HashMap<String, EncryptionProfile>,
        }
        let doc: ProfilesDoc = toml::from_str(&raw).map_err(|e| {
            mtw_core::MtwError::Config(format!(
                "torrent: parse profiles_file '{}': {}",
                path.display(),
                e
            ))
        })?;
        for (k, v) in doc.profiles {
            self.profiles.entry(k).or_insert(v);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_has_clear_profile() {
        let cfg = TorrentConfig::default();
        assert!(cfg.enabled);
        assert!(cfg.profiles.contains_key("clear"));
        assert!(matches!(
            cfg.profiles["clear"],
            EncryptionProfile::Direct
        ));
    }

    #[test]
    fn parse_config_with_inline_profiles() {
        let toml_src = r#"
enabled = true
http_listen = "127.0.0.1:9000"
default_profile = "tor-trackers"
storage_quota_bytes = 1073741824

[profiles.clear]
type = "direct"

[profiles.tor-trackers]
type = "tor_socks"
socks5 = "127.0.0.1:9050"

[streaming]
prefetch_window_bytes = 33554432
"#;
        let cfg: TorrentConfig = toml::from_str(toml_src).unwrap();
        assert_eq!(cfg.http_listen, "127.0.0.1:9000");
        assert_eq!(cfg.default_profile, "tor-trackers");
        assert_eq!(cfg.storage_quota_bytes, Some(1024 * 1024 * 1024));
        assert_eq!(cfg.profiles.len(), 2);
        assert_eq!(cfg.streaming.prefetch_window_bytes, 32 * 1024 * 1024);
    }

    #[test]
    fn profile_availability() {
        assert!(EncryptionProfile::Direct.is_available());
        assert!(EncryptionProfile::TorSocks {
            socks5: "127.0.0.1:9050".into()
        }
        .is_available());
        assert!(!EncryptionProfile::Wireguard {
            private_key: "k".into(),
            peer_public_key: "p".into(),
            endpoint: "e:1".into(),
            allowed_ips: vec![],
            dns: vec![],
        }
        .is_available());
    }

    #[test]
    fn resolved_storage_path_falls_back_to_xdg() {
        let cfg = TorrentConfig::default();
        let p = cfg.resolved_storage_path();
        assert!(p.ends_with("mtwrequest/torrents"));
    }

    #[test]
    fn loads_profiles_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("profiles.toml");
        std::fs::write(
            &path,
            r#"
[profiles.tor]
type = "tor_socks"
socks5 = "127.0.0.1:9050"
"#,
        )
        .unwrap();
        let mut cfg = TorrentConfig::default();
        cfg.profiles_file = Some(path);
        cfg.load_profiles_file().unwrap();
        assert!(cfg.profiles.contains_key("tor"));
    }
}
